project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "assets/logo/Horizontal_Lockup_White.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - who-we-are.qmd
      - resources.qmd
      - posts.qmd
      - join.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

