---
title: "About"
---

Response diversity is variation in how organisms respond to environmental change. A diversity of responses ensures that when some organisms are negatively affected, others experience positive effects. This should lead to greater stability of ecological communities and ecosystems. The ways in which response diversity is studied and measured are diverse and span across multiple scales and environments. Because of this, our understanding of whether there are general "rules" and "metrics" with respect to response diversity is still limited.

The aims of the Response Diversity Network currently include:

-   To organise and accelerate scientific advances about response diversity.

-   To promote the inclusion of response diversity in monitoring and assessment of biodiversity change.

-   To provide clear and accessible information about response diversity to relevant individuals and organisations.

The network should evolve, and as it does, these aims and how they are approached can evolve as well. The process for such change should be as open and inclusive as possible.
